<?php

/* PER ANDARE A LEGGERE DEI VALORI NELLA QUERY E NELLE TABELLE

UTILIZZO LA FUNZIONE:

mysqli_fetch_assoc(...);

AD ESEMPIO ORA CREO UNA VARIABILE CHE VA INTERROGARE UN QUERY DA ME CREATA*/

$interrogoRow=mysqli_fetch_assoc($query);

// CON LA VARIABILE CHE SEGUE USO LA FUNZIONE PER INTERROGARE E LEGGERE UN DATO SPECIFICO

$confermaInterrogazione=$interrogoRow['elementoDiUnaTabella'];

//POTREI QUINDI USARLA PER FARE DEI TEST CON DEGLI IF ETC...



 ?>
